### ISSUE TITLE
[build] C:/xxxxxxx/./library/USB2XXX.dll: file not recognized: File format not recognized

### ISSUE THREAD

**Issue by leduc900** [jianhun9527/UDS_UNIVERSAL_HOST#2]
Any idea why I am getting this error?

**Comment by jianhun9527** [comment]
It seems to me that the cmake rules may have been added incorrectly, and that dynamic libraries should have been added
Since I haven't encountered this problem, if you need to analyze it further, you can show me the project

**Comment by leduc900** [comment]
[CMakeLists.zip](https://github.com/jianhun9527/UDS_UNIVERSAL_HOST/files/15428128/CMakeLists.zip)

![24-05-2024 17-55-11](https://github.com/jianhun9527/UDS_UNIVERSAL_HOST/assets/109586212/124bdd7b-641e-4f01-b425-7757e7090be3)

**Comment by leduc900** [comment]
Fixed. I was using incorrect gcc compiler (32 bits). 

![25-05-2024 12-51-53](https://github.com/jianhun9527/UDS_UNIVERSAL_HOST/assets/109586212/6167bf29-3c0d-4325-8c59-77995b9c292e)

**Comment by jianhun9527** [comment]
Congratulations, you succeeded
All dynamic libraries in my project are 64-bit, you can encapsulate them yourself if needed
