### ISSUE TITLE
libGenerateKey.dll

### ISSUE THREAD

**Issue by leduc900** [jianhun9527/UDS_UNIVERSAL_HOST#3]
Could you please share the source code of 

https://github.com/jianhun9527/UDS_UNIVERSAL_HOST/blob/CAN_LIN_Tool_V5740/library/libGenerateKey.dll

**Comment by jianhun9527** [comment]
The source code of the dll is not important, you only need to focus on [GenerateKeyEx.h](https://github.com/jianhun9527/UDS_UNIVERSAL_HOST/blob/CAN_LIN_Tool_V5740/library/GenerateKeyEx.h) in the library folder
The main focus is on the two function prototypes inside, you can just implement the same functions in the embedded bootloader

**Comment by jianhun9527** [comment]
The source code of the dll is not important, you only need to focus on [GenerateKeyEx.h](https://github.com/jianhun9527/UDS_UNIVERSAL_HOST/blob/CAN_LIN_Tool_V5740/library/GenerateKeyEx.h) in the library folder
The main focus is on the two function prototypes inside, you can just implement the same functions in the embedded bootloader
